### ISSUE TITLE
Add support for additional tags to Endpoint Interface

### ISSUE THREAD

**Issue by ankitrm** [traveloka/terraform-aws-privatelink-consumer#12]
In AWS UI, VPC Endpoints created using this module doesn't have any provider AWS account ID information.

Suggestion: Add mandatory tag named (lets say) `ProviderAccountAlias` to provide AWS account id for producer VPC Endpoint Service.

**Comment by febryantonius** [comment]
Hi @SiahaanBernard @sumodirjo, need your comment on this. To highlight the problem, currently we can't easily know in which account the VPC Endpoint connect to

**Comment by sshvetsov** [comment]
I'm not exactly clear why this has to be a _mandatory_ tag, but I don't see a problem with allowing additional free form tags or and _optional_ `ProviderAccountAlias` tag.

**Comment by sshvetsov** [comment]
I also recommend opening a Product Feature Request (PFR) with AWS, since being to able to tell which the ID of the AWS account of the Service Owner by looking at Interface Endpoint metadata, is indeed important.

**Comment by febryantonius** [comment]
I considered to make it mandatory to enforce the user to put the information when creating the VPC Endpoint but I forgot to consider creating a PFR for it. I agree with the optional additional free form tags so the user can add any tags that will be beneficial for them

**Comment by sshvetsov** [comment]
The reason I'm hesitant to make this tag mandatory is that it would be a "breaking change" and would require major version change. I'm OK with making it a standard "optional" tag, however.

**Comment by febryantonius** [comment]
Noted, I got your point on that.

**Comment by nuradhi** [comment]
I'm closing this issue. Add additional tags has been support on v0.2.2. Thank you
